version: '3'
services:
  locator:
    container_name: locator
    build: 
      context: java 
      dockerfile: Dockerfile
    image: trash-transformers/locate:latest
    ports: 
      - 8081:8081
  classifier:
    container_name: classifier
    build: 
      context: application
      dockerfile: Dockerfile
    image: trash-transformers/classify:latest
    ports: 
      - 8000:80
  app:
    container_name: app
    build: 
      context: web 
      dockerfile: Dockerfile
    image: trash-transformers/app:latest
    ports: 
      - 4200:4200
    depends_on:
    - locator
    - classifier


